deploy:
  provider: pypi
  user: isaidyep
  password:
    secure: qQ2Rrv8e7XUIEkSVX6t/locE1BXWKGhN31hts5sXLSyPvKFDkXmZz8TLaVtnI1YV6ldmqQUaidQrS/937eWW8+Jh7JgAjt4Xe2R4yA3w7lbY3zk6XkyAK9edsGcugZxxAQY+yE0CsUdkSA8yh4Ad56owwOn3cNBc9Wth/epTzdWyA6sD2BslI/cbJXrLxwYwePT7K8PEStd52sm6AGukkas8RMbXQfavPWm3qgnin4fSi1c3VyxF+rgQC0/vvv1VklE3pFv52/5JFkHP8DPbGBseNQ2ECXm2NFqdt6Vva5mXfPwObr89SoHTv4FnrjQQ+T3piqTZRKvBFHVmo0uLZt9RXnyGtviRyQ2QFTiFPLkdZLVAvTNyMHrLlL7zi3XqcbnDIv6hQFYWMWbck3n2iy2xJwkQvDJgxjkbBw7/XxotiwJZK5j+JukD2VKcj7aQpORrV8zQsb7OKuC3G9FBXQUcn41iihDTfU8dqejOAucqNaNq2B5AlY2cCnXfIXlDlPVBHGNleAErwchPZdKb2RZwCK1Ft4g4/WYN3smvpzttYWQnjmXvCTEyGkayIKJaFe1p8B4hGNmY+PPzeUpPcxRsxcVbyVWtc2Gcx50ThvZ6W2tbEKfyg4d3PwwNxucL3ipIsKkD9KMnEuQSQ5zFtJavMePzs4y1WlWGiN7eBWw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: MirkoRossini/zanna
install: pip install -U tox-travis==0.6
language: python
python:
- 3.5
- 3.6
- 3.6-dev
script: tox
